name: Test Job

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  avro_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run gradle
        run: ./gradlew generateAvro assembleAndroidTest
